//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnLanChat
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using System.Threading;
	public class IThreads
	{
		public Thread UDP_receving;

		public Thread TCP_receving;

		public Thread Broadcast;

		public object BROADCAST_SENDING;

		public object BROADCAST_RECEVING;

	}
}

