//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace OnLanChat
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class UserList
	{
		public virtual void getSelected()
		{
			throw new System.NotImplementedException();
		}

		public virtual void getUsers()
		{
			throw new System.NotImplementedException();
		}

	}
}

